import suraMetaRaw from "../data/quran/sura-meta.json";
import arabicData from "../data/quran/arabic.json";
import russianData from "../data/quran/russian.json";
import translitData from "../data/quran/translit.json";

const RUS_NAMES = {
  1: "Аль-Фатиха",
  2: "Аль-Бакара",
  3: "Аль-Имран",
  4: "Ан-Ниса",
  5: "Аль-Маида",
  6: "Аль-Анам",
  7: "Аль-Араф",
  8: "Аль-Анфаль",
  9: "Ат-Тауба",
  10: "Юнус",
  11: "Худ",
  12: "Юсуф",
  13: "Ар-Рад",
  14: "Ибрахим",
  15: "Аль-Хиджр",
  16: "Ан-Нахль",
  17: "Аль-Исра",
  18: "Аль-Кахф",
  19: "Марьям",
  20: "Та-Ха",
  21: "Аль-Анбия",
  22: "Аль-Хадж",
  23: "Аль-Муминун",
  24: "Ан-Нур",
  25: "Аль-Фуркан",
  26: "Аш-Шуара",
  27: "Ан-Намль",
  28: "Аль-Касас",
  29: "Аль-Анкабут",
  30: "Ар-Рум",
  31: "Лукман",
  32: "Ас-Саджда",
  33: "Аль-Ахзаб",
  34: "Саба",
  35: "Фатир",
  36: "Йа Син",
  37: "Ас-Саффат",
  38: "Сад",
  39: "Аз-Зумар",
  40: "Гафир",
  41: "Фуссилят",
  42: "Аш-Шура",
  43: "Аз-Зухруф",
  44: "Ад-Духан",
  45: "Аль-Джасия",
  46: "Аль-Ахкаф",
  47: "Мухаммад",
  48: "Аль-Фатх",
  49: "Аль-Худжурат",
  50: "Каф",
  51: "Аз-Зариат",
  52: "Ат-Тур",
  53: "Ан-Наджм",
  54: "Аль-Камар",
  55: "Ар-Рахман",
  56: "Аль-Вакиа",
  57: "Аль-Хадид",
  58: "Аль-Муджадала",
  59: "Аль-Хашр",
  60: "Аль-Мумтахана",
  61: "Ас-Сафф",
  62: "Аль-Джумуа",
  63: "Аль-Мунафикун",
  64: "Ат-Тагабун",
  65: "Ат-Талак",
  66: "Ат-Тахрим",
  67: "Аль-Мульк",
  68: "Аль-Калам",
  69: "Аль-Хакка",
  70: "Аль-Мааридж",
  71: "Нух",
  72: "Аль-Джинн",
  73: "Аль-Муззаммиль",
  74: "Аль-Муддассир",
  75: "Аль-Кыяма",
  76: "Аль-Инсан",
  77: "Аль-Мурсалят",
  78: "Ан-Наба",
  79: "Ан-Назиат",
  80: "Абаса",
  81: "Ат-Таквир",
  82: "Аль-Инфитар",
  83: "Аль-Мутаффифин",
  84: "Аль-Иншикак",
  85: "Аль-Бурудж",
  86: "Ат-Тарик",
  87: "Аль-Аля",
  88: "Аль-Гашия",
  89: "Аль-Фаджр",
  90: "Аль-Балад",
  91: "Аш-Шамс",
  92: "Аль-Лейль",
  93: "Ад-Духа",
  94: "Аш-Шарх",
  95: "Ат-Тин",
  96: "Аль-Аляк",
  97: "Аль-Кадр",
  98: "Аль-Баййина",
  99: "Аз-Зальзаля",
  100: "Аль-Адият",
  101: "Аль-Кариа",
  102: "Ат-Такасур",
  103: "Аль-Аср",
  104: "Аль-Хумаза",
  105: "Аль-Филь",
  106: "Курайш",
  107: "Аль-Маун",
  108: "Аль-Каусар",
  109: "Аль-Кафирун",
  110: "Ан-Наср",
  111: "Аль-Масад",
  112: "Аль-Ихлас",
  113: "Аль-Фалак",
  114: "Ан-Нас",
};

const RUS_TRANSLATIONS = {
  1: "Открывающая",
  2: "Корова",
  3: "Семейство Имрана",
  4: "Женщины",
  5: "Трапеза",
  6: "Скот",
  7: "Ограды",
  8: "Трофеи",
  9: "Покаяние",
  10: "Юнус",
  11: "Худ",
  12: "Юсуф",
  13: "Гром",
  14: "Ибрахим",
  15: "Хиджр",
  16: "Пчёлы",
  17: "Перенёс ночью",
  18: "Пещера",
  19: "Марьям",
  20: "Та Ха",
  21: "Пророки",
  22: "Хадж",
  23: "Верующие",
  24: "Свет",
  25: "Различение",
  26: "Поэты",
  27: "Муравьи",
  28: "Рассказ",
  29: "Паук",
  30: "Римляне",
  31: "Лукман",
  32: "Поклон",
  33: "Союзники",
  34: "Саба",
  35: "Творец",
  36: "Йа Син",
  37: "Стоящие в ряд",
  38: "Сад",
  39: "Толпы",
  40: "Прощающий",
  41: "Разъяснены",
  42: "Совет",
  43: "Украшения",
  44: "Дым",
  45: "Коленопреклонённая",
  46: "Барханы",
  47: "Мухаммад",
  48: "Победа",
  49: "Комнаты",
  50: "Каф",
  51: "Рассеивающие",
  52: "Гора",
  53: "Звезда",
  54: "Луна",
  55: "Милостивый",
  56: "Падающее",
  57: "Железо",
  58: "Препирающаяся",
  59: "Сбор",
  60: "Испытуемая",
  61: "Ряды",
  62: "Собрание",
  63: "Лицемеры",
  64: "Взаимное обделение",
  65: "Развод",
  66: "Запрещение",
  67: "Власть",
  68: "Письменная трость",
  69: "Неминуемое",
  70: "Ступени",
  71: "Нух",
  72: "Джинны",
  73: "Закутавшийся",
  74: "Завернувшийся",
  75: "Воскресение",
  76: "Человек",
  77: "Посылаемые",
  78: "Весть",
  79: "Исторгающие",
  80: "Нахмурился",
  81: "Скручивание",
  82: "Раскалывание",
  83: "Обвешивающие",
  84: "Разверзнётся",
  85: "Созвездия",
  86: "Ночной путник",
  87: "Высочайший",
  88: "Покрывающее",
  89: "Заря",
  90: "Город",
  91: "Солнце",
  92: "Ночь",
  93: "Утро",
  94: "Раскрытие",
  95: "Смоковница",
  96: "Сгусток",
  97: "Предопределение",
  98: "Ясное знамение",
  99: "Землетрясение",
  100: "Скачущие",
  101: "Великое бедствие",
  102: "Приумножение",
  103: "Время",
  104: "Хулитель",
  105: "Слон",
  106: "Курайшиты",
  107: "Подаяние",
  108: "Изобилие",
  109: "Неверующие",
  110: "Помощь",
  111: "Пальмовые волокна",
  112: "Очищение веры",
  113: "Рассвет",
  114: "Люди",
};

const REVELATION_MAP = {
  Meccan: "Мекканская",
  Medinan: "Мединская",
};

export const surahs = suraMetaRaw.map((s) => ({
  number: s.n,
  arabicName: s.ar,
  russianName: RUS_NAMES[s.n] ?? s.en,
  translation: RUS_TRANSLATIONS[s.n] ?? s.enT,
  ayahCount: s.count,
  revelation: REVELATION_MAP[s.rev] ?? s.rev,
}));

// Tanzil prepends bismillah to the first ayah of every sura except 1 (which IS bismillah) and 9.
// Strip it for display so we can render the standalone bismillah header without duplication.
const BISMILLAH_VARIANTS = [
  "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
  "بِسْمِ ٱللَّٰهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
  "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
];
const BOM = "﻿";

function stripLeadingBismillah(text) {
  if (!text) return text;
  let s = text.startsWith(BOM) ? text.slice(1) : text;
  for (const variant of BISMILLAH_VARIANTS) {
    if (s.startsWith(variant)) {
      return s.slice(variant.length).trimStart();
    }
  }
  return s;
}

export function getSura(suraNumber) {
  const meta = surahs[suraNumber - 1];
  if (!meta) return null;
  const ar = arabicData[suraNumber - 1] ?? [];
  const ru = russianData[suraNumber - 1] ?? [];
  const tr = translitData[suraNumber - 1] ?? [];
  const stripBismillah = suraNumber !== 1 && suraNumber !== 9;
  const ayahs = ar.map((arabic, i) => ({
    number: i + 1,
    arabic: stripBismillah && i === 0 ? stripLeadingBismillah(arabic) : arabic,
    translation: ru[i] ?? "",
    transliteration: tr[i] ?? "",
  }));
  return { ...meta, ayahs };
}

export const JUZ_BOUNDARIES = [
  { juz: 1, start: { sura: 1, ayah: 1 } },
  { juz: 2, start: { sura: 2, ayah: 142 } },
  { juz: 3, start: { sura: 2, ayah: 253 } },
  { juz: 4, start: { sura: 3, ayah: 93 } },
  { juz: 5, start: { sura: 4, ayah: 24 } },
  { juz: 6, start: { sura: 4, ayah: 148 } },
  { juz: 7, start: { sura: 5, ayah: 82 } },
  { juz: 8, start: { sura: 6, ayah: 111 } },
  { juz: 9, start: { sura: 7, ayah: 88 } },
  { juz: 10, start: { sura: 8, ayah: 41 } },
  { juz: 11, start: { sura: 9, ayah: 93 } },
  { juz: 12, start: { sura: 11, ayah: 6 } },
  { juz: 13, start: { sura: 12, ayah: 53 } },
  { juz: 14, start: { sura: 15, ayah: 1 } },
  { juz: 15, start: { sura: 17, ayah: 1 } },
  { juz: 16, start: { sura: 18, ayah: 75 } },
  { juz: 17, start: { sura: 21, ayah: 1 } },
  { juz: 18, start: { sura: 23, ayah: 1 } },
  { juz: 19, start: { sura: 25, ayah: 21 } },
  { juz: 20, start: { sura: 27, ayah: 56 } },
  { juz: 21, start: { sura: 29, ayah: 46 } },
  { juz: 22, start: { sura: 33, ayah: 31 } },
  { juz: 23, start: { sura: 36, ayah: 28 } },
  { juz: 24, start: { sura: 39, ayah: 32 } },
  { juz: 25, start: { sura: 41, ayah: 47 } },
  { juz: 26, start: { sura: 46, ayah: 1 } },
  { juz: 27, start: { sura: 51, ayah: 31 } },
  { juz: 28, start: { sura: 58, ayah: 1 } },
  { juz: 29, start: { sura: 67, ayah: 1 } },
  { juz: 30, start: { sura: 78, ayah: 1 } },
];

export function getSurasInJuz(juzNumber) {
  const start = JUZ_BOUNDARIES.find((j) => j.juz === juzNumber);
  const end = JUZ_BOUNDARIES.find((j) => j.juz === juzNumber + 1);
  if (!start) return [];
  const startSura = start.start.sura;
  const endSura = end ? end.start.sura : 114;
  return surahs.filter((s) => s.number >= startSura && s.number <= endSura);
}
